### ISSUE TITLE
Formatting errors etc. To end of chapter 1.

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/Thesis#12]
1 - I agree CC-BY-SA is better than (c)
2 - Appendices. They aren't really supplementary data, so much as supplementary information or materials
3 - Some of the dots in the tables list are misaligned because you have full stops in the captions. Remove the full stops to fix e.g. "[My figure.] Figure showing X and Y" you need to remove the . after My figure
4 - Typo in the first lien of data availability. GitHug sounds cool though!
5 - Top of page 2: "The scarcity of trees combining living and fossil" (rather than fossils). Check for this typo as you seem to have introduced it recently! It's living and fossil species. NOT living and fossils species.
6 - line3 of page 2. You didn't finish the sentence!!! "probably due to the fact that palaeontologists and neontologists." Do what? Construct phylogenies in different ways?
7 - page 2 second paragraph: "relationships among lineages" not relations
8 - Start of page 3 - "(Chapter 4" is missing a bracket round it
9 - It'd be good if the intro didn't go on to page 5. Could you drop some citations or something where you've got long lists? Or the page before could you save space by putting all the refs at the end of the sentence then you don't need all the e.g.s (By using all the available neontological and palaeontological
data, this method can greatly improve the estimation of divergence events (e.g. Ronquist
et al., 2012a), evolutionary rates (e.g. Beck and Lee, 2014), tree topology (e.g. Dembo et al.,
2015), trait evolution (e.g. Slater, 2013) and even speciation processes (e.g. Wood et al.,
2013). Not essential but worth a quick go!

**Comment by TGuillerme** [comment]
Thanks a lot, will work on that.
