### ISSUE TITLE
Formatting errors etc. To end of chapter 5.

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/Thesis#13]
1 - Footnotes need commas between them and preferably no gaps e.g. Total evidence chapter name<sup>1,2</sup> Otherwise it looks like footnote 12!
2 - I'd have the reference read Guillerme, T & Cooper, N. rather than our full names
3 - Figure looks odd with the legend underneath but no figure label. There's not enough info there for it to be useful. I'd be tempted to leave that out, or incorporate it into the chapter, or the overall intro or discussion. You don't need chapter header pictures (though I do like the one for Chapter 4).
4 - Get rid of the keywords
5 - p32, I'd probably force the discussion to start after those two figures.
6 - figure 3.1 seems really large given it's not that interesting, make it smaller?
7 - Fig 3.2 NEXUS is always all capitals. Also isn't it he Paleobiology Database not Paleo Database (PBDB)
8 - Table 3.1. Bold the column headers and centre "Coverage". Also would be good if at least part of the table was under the legend so maybe force it to start on a new page?
9 - p57. I'd give the Gould quote a footnote so you can add a citation (with page number if possible). Also don't give the date of submission. I'd be tempted not to say where it was submitted, just say submitted for publication. Then if it comes back straight away from PLoS there's no embarrassment at the viva! :)
10 - p 58 - get rid of the keywords!
11 - Can you tidy up Figure 4.1's bottom axis? Carboniferous is cut off. I know the right hand side is hard to fix.
12 - pg 68. 4.2.6 Testing the effects of the K-Pg extinction event (rather than just extinction)?

**Comment by TGuillerme** [comment]
Done with these, thanks a lot! :radio: :nut_and_bolt:
