### ISSUE TITLE
General point about sections in chapters

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/Thesis#14]
You should be consistent. So each chapter should have similar sections. 

Conclusions in TEM chapter is a subsection, but it's a subsubsection in STD. Pick one and stick to it! Also there are no conclusions in Missing mammals. But you can ignore that I think.

Also STD has Methods where the others have Materials and Methods - I'd fix that.

**Comment by nhcooper123** [comment]
FYI I only mean the data chapters (2-5)

**Comment by TGuillerme** [comment]
Done. I've put "Methods" for all and "Conclusion" is now a sub(sub)section for all.
