### ISSUE TITLE
References

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/Thesis#15]
Please check carefully. Lots of formatting errors. Things that should be capitalised or in italics etc. For books you need publisher and the city it was published in. 

Reference formatting is the first place i look when determining quality of thesis presentation.

**Comment by TGuillerme** [comment]
Hmmm for that one I never know what's the rule (and I know you commented on it many time).

Books: titles in italic + publisher and the city it was published in ?
Papers: titles with first letter of each word in capital letters?

**Comment by nhcooper123** [comment]
Papers, no you don't need the title capitalised. 

Guillerme T., and Cooper N. Year. Our paper title. Journal (usually in italics and with each word starting with a capital letter). Vol (usually bold): page:page. 
As long as you are consistent it doesn't matter too much. BUT need to capitalise the names of species, species groups etc. Reptilia, Squamata, etc. Sometimes you do, sometimes you don't. That's the problem.

For books, again whether you italicise or not doesn't matter as long as you are consistent:

Guillerme, T. Year. My book on science (usually in italics). Publishing Company: New York.

Or 

Guillerme T. Year. My chapter in this book. In: My book on science (italics). Publishing Company: New York. pages X:X

**Comment by TGuillerme** [comment]
Ok, thanks. Will do that (still on editing the chapters).

**Comment by TGuillerme** [comment]
That's done. Might be some more details I'll pick up when proof reading.
