### ISSUE TITLE
Appendices

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/Thesis#16]
- You have the title of the chapter, then underneath say "The following section contains supplementary results to the chapter “Effects of missing data on topological inference using a Total Evidence approach”. No need to repeat it! Just say "supplementary results to Chapter 2". Same for 3 and 4.
- Appendix B for Chapter 3 needs a bit of explanatory text between each element to explain what each thing is showing, like for Chapter 2. Also isn't the big table in the main text now? Where are the PD results you mention. Fix this please.
- Appendix C. Also needs a tidy up. Missing full stop on page one. Eutheria not Eutherian. every tip not every tips. dataset not data set. Ma not Mya. 
- Unfortunately I think I might need to go through Appendix B and C when you've tidied them to make sure they are english-ified. A lot of s's in weird places... I'm assuming Appendix A is fine as we went through that for Syst biol

**Comment by TGuillerme** [comment]
I've edited the supplementary with more details and links to the main chapters (for the [missing data paper](https://github.com/TGuillerme/Thesis/blob/master/Supplementaries/Missing_mammals.tex) and the [STD one](https://github.com/TGuillerme/Thesis/blob/master/Supplementaries/STD_draft.tex)). I'm now going to read the thesis backwards for typo checking. Joy. :kimono::fried_shrimp:
