### ISSUE TITLE
Second row editing on the intro-intro

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/Thesis#2]
Dear Dr Cooper,

I've dealt with your few comments for the [intro-intro](https://github.com/TGuillerme/Thesis/blob/master/introduction.tex). If you have time to have a look at it (no rush) it means only the STD chapter and the discussion are left to do!

Yay! :smile_cat: :pig: :helicopter:

**Comment by nhcooper123** [comment]
Done! :pineapple:
