### ISSUE TITLE
Thesis discussion edits

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/Thesis#8]
Hi boss, just finished editing the [discussion](https://github.com/TGuillerme/Thesis/blob/master/discussion.tex). I still not entirely happy with it but I think I have this feeling every time I write a discussion: it's not bringing much (i.e. there is a problem X but Y solves it so maybe X is less a problem)...
Cheers! :aerial_tramway::closed_lock_with_key:

**Comment by TGuillerme** [comment]
Ok, I've updated the [discussion](https://github.com/TGuillerme/Thesis/blob/master/discussion.tex) with the clarifications you've asked. I think it's still not as good as the discussions for each individual chapters but it might be enough for the thesis... :alien: :runner:

If you're happy with these comments, and if you have time this week, you can also have an overall look at the thesis (e.g. placement of figures or chapters names) to tell me if there are some major problems. You might not want to read the full thing since you did it some many times already (I'll get the folks here + myself to have a look at the typos). It shouldn't take too long. That way you can go to holiday/week end with the feeling of having one big thing out of the way!  :camel: :dango: :ghost:

**Comment by nhcooper123** [comment]
Done! :smiley_cat:

**Comment by TGuillerme** [comment]
Woohooohooo! Thanks a lot! :star2::snowman::fireworks::tangerine:
