### ISSUE TITLE
Thesis abstract edits

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/Thesis#9]
I've also dealt with your comments on the [summary](https://github.com/TGuillerme/Thesis/blob/master/summary.tex) (or abstract). Getting there! :thought_balloon::globe_with_meridians:

**Comment by nhcooper123** [comment]
As you're not around to merge the stuff I sent on the Discussion I can't pull the most recent version of this, so here are comments:

line 14: would not biase = should not bias
line 17: Previous studies show support for an effect of the K-Pg extinction event on mammalian diversification when using palaeontological data but no support using neontological data.
line 22 - % NC: I like this sentence (it doesn't matter if the abstract goes over one page), but removing typos:
These results refute the popular belief that mammals only began diversifying after the extinction of the non-avian dinosaurs, and shows the advantage of using living and fossil species to answer macroevolutionary questions.
line 25: Finally, I discuss future avenues of research for improving analyses that include living and fossil species as well as the advantages of using both living and fossil taxa when investigating macroevolutionary questions.
line 26: I argue that including both sources of data in macroevolutionary studies is a really promising way to increase our knowledge in biology in general.
% NC: Hmm increase our knowledge of biology in general? Not really what you talk about at all. Maybe:
I argue that all macroevolutionary studies should include both types of data to advance our understanding of biodiversity.

:+1: 

Then that's done I think. I don't need to see this again. I'd like another quick look at the Discussion then after that just send me the whole thing so I can have a look at the formatting etc. Makes sure you get someone to spell/grammar/english check everything. Probably best to give people a chapter each, it's hard to concentrate for longer than that.

YAY!

:star2:
